version: "3.7"

services:
  server-prod:
    build: ./server
    command: uvicorn app.main:app --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./server/:/usr/src/app/
    ports:
      - 8003:8000

  client-prod:
    build:
      context: client
      args:
        - API_URL=http://192.168.1.14:8003
    ports:
      - 5051:80
